FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build
# Ensure database is migrated or generated
RUN npx prisma generate

EXPOSE 3001
CMD ["npm", "start"]
